events {}

http {
    upstream backend {
        # Balanceo round-robin (por defecto): alterna cada request entre server1 y server2
        server app1:8080;
        server app2:8080;
    }

    server {
        listen 80;

        location /datos {
            proxy_pass http://backend/datos;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
