spring.application.name=examenfinal

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/examenad}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

server.port=8080
server.name=${SERVER_NAME:server-default}
